// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/api"
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/api/handler"
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/config"
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/database"
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/repository"
	"github.com/abhinandpn/MicroServices-Demo/User-Service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	db, err := database.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userReporitory := repository.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userReporitory)
	userHandler := handler.NewUserUseHandler(userUsecase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
