// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/api"
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/api/handler"
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/config"
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/database"
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/repository"
	"github.com/abhinandpn/MicroServices-Demo/Admin-Service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	db, err := database.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := repository.NewAdminRepository(db)
	adminUsecase := usecase.NewAdminUseCase(adminRepository)
	adminhandler := handler.NewAdminHandler(adminUsecase)
	serverHTTP := http.NewServerHTTP(adminhandler)
	return serverHTTP, nil
}
